/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package mchdelaware.ranger;

import javax.swing.JFrame;

/**
 *
 * @author marek
 */
public class RangerFrame extends javax.swing.JFrame {

    /**
     * Creates new form RangerFrame
     */
    public RangerFrame() {
        initComponents();
        initUI();
    }

    private void initUI() {
        drawingPanel = new DrawingPanel(this);
        CenterPanel.add(drawingPanel);

        setTitle("Java 2D Ranger");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        GunPanel = new javax.swing.JPanel();
        degYGLabel = new javax.swing.JLabel();
        grayCodeGL = new javax.swing.JLabel();
        degYGvalue = new javax.swing.JLabel();
        grayCodeYG = new javax.swing.JLabel();
        degYGSpinner = new javax.swing.JSpinner();
        gunMoveDir = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        BottomPanel = new javax.swing.JPanel();
        degYLabel = new javax.swing.JLabel();
        grayCodeL = new javax.swing.JLabel();
        degYvalue = new javax.swing.JLabel();
        grayCodeY = new javax.swing.JLabel();
        degYSpinner = new javax.swing.JSpinner();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setName(""); // NOI18N
        MainPanel.setLayout(new java.awt.BorderLayout());

        TopPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TopPanel.setMaximumSize(new java.awt.Dimension(9999, 250));
        TopPanel.setMinimumSize(new java.awt.Dimension(200, 50));
        TopPanel.setName(""); // NOI18N
        TopPanel.setPreferredSize(new java.awt.Dimension(2000, 250));
        TopPanel.setLayout(new java.awt.BorderLayout());

        GunPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GunPanel.setMaximumSize(new java.awt.Dimension(2147483647, 250));
        GunPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        GunPanel.setOpaque(false);
        GunPanel.setPreferredSize(new java.awt.Dimension(1665, 100));
        GunPanel.setLayout(new java.awt.GridLayout(3, 8));

        degYGLabel.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        degYGLabel.setText("degY [deg]");
        degYGLabel.setMaximumSize(new java.awt.Dimension(100, 20));
        degYGLabel.setMinimumSize(new java.awt.Dimension(60, 10));
        degYGLabel.setPreferredSize(new java.awt.Dimension(60, 15));
        GunPanel.add(degYGLabel);

        grayCodeGL.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        grayCodeGL.setText("Gray code for Y");
        GunPanel.add(grayCodeGL);

        degYGvalue.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        degYGvalue.setText("0.0");
        degYGvalue.setMaximumSize(new java.awt.Dimension(100, 20));
        degYGvalue.setMinimumSize(new java.awt.Dimension(60, 10));
        degYGvalue.setPreferredSize(new java.awt.Dimension(60, 15));
        GunPanel.add(degYGvalue);

        grayCodeYG.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        grayCodeYG.setText("00");
        GunPanel.add(grayCodeYG);

        degYGSpinner.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        degYGSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, -180.0d, 179.9d, 0.1d));
        degYGSpinner.setDoubleBuffered(true);
        degYGSpinner.setMaximumSize(new java.awt.Dimension(100, 20));
        degYGSpinner.setMinimumSize(new java.awt.Dimension(60, 10));
        degYGSpinner.setPreferredSize(new java.awt.Dimension(60, 15));
        degYGSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                degYGSpinnerStateChanged(evt);
            }
        });
        GunPanel.add(degYGSpinner);

        gunMoveDir.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        gunMoveDir.setText("0");
        GunPanel.add(gunMoveDir);

        TopPanel.add(GunPanel, java.awt.BorderLayout.PAGE_END);

        MainPanel.add(TopPanel, java.awt.BorderLayout.NORTH);

        CenterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CenterPanel.setPreferredSize(new java.awt.Dimension(2000, 500));
        CenterPanel.setLayout(new java.awt.BorderLayout());
        MainPanel.add(CenterPanel, java.awt.BorderLayout.CENTER);

        BottomPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BottomPanel.setMaximumSize(new java.awt.Dimension(2147483647, 250));
        BottomPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        BottomPanel.setOpaque(false);
        BottomPanel.setPreferredSize(new java.awt.Dimension(1665, 100));
        BottomPanel.setLayout(new java.awt.GridLayout(3, 8));

        degYLabel.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        degYLabel.setText("degY [deg]");
        degYLabel.setMaximumSize(new java.awt.Dimension(100, 20));
        degYLabel.setMinimumSize(new java.awt.Dimension(60, 10));
        degYLabel.setPreferredSize(new java.awt.Dimension(60, 15));
        BottomPanel.add(degYLabel);

        grayCodeL.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        grayCodeL.setText("Gray code for Y");
        BottomPanel.add(grayCodeL);

        degYvalue.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        degYvalue.setText("0.0");
        degYvalue.setMaximumSize(new java.awt.Dimension(100, 20));
        degYvalue.setMinimumSize(new java.awt.Dimension(60, 10));
        degYvalue.setPreferredSize(new java.awt.Dimension(60, 15));
        BottomPanel.add(degYvalue);

        grayCodeY.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        grayCodeY.setText("00");
        BottomPanel.add(grayCodeY);

        degYSpinner.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        degYSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, -180.0d, 179.9d, 0.1d));
        degYSpinner.setDoubleBuffered(true);
        degYSpinner.setMaximumSize(new java.awt.Dimension(100, 20));
        degYSpinner.setMinimumSize(new java.awt.Dimension(60, 10));
        degYSpinner.setPreferredSize(new java.awt.Dimension(60, 15));
        degYSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                degYSpinnerStateChanged(evt);
            }
        });
        BottomPanel.add(degYSpinner);

        MainPanel.add(BottomPanel, java.awt.BorderLayout.PAGE_END);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void degYSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_degYSpinnerStateChanged
        // TODO add your handling code here:
        Number value = (Number) degYSpinner.getValue();
        double degY = value.doubleValue();
        degYvalue.setText("" + degY);
        drawingPanel.setSigthDegY(degY);

        drawingPanel.revalidate();
        drawingPanel.repaint();
    }//GEN-LAST:event_degYSpinnerStateChanged

    private void degYGSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_degYGSpinnerStateChanged
        // TODO add your handling code here:
        Number value = (Number) degYGSpinner.getValue();
        double degY = value.doubleValue();
        degYGvalue.setText("" + degY);
        drawingPanel.setSigthDegG(degY);

        drawingPanel.revalidate();
        drawingPanel.repaint();
    }//GEN-LAST:event_degYGSpinnerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RangerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RangerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RangerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RangerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RangerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel GunPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JLabel degYGLabel;
    private javax.swing.JSpinner degYGSpinner;
    private javax.swing.JLabel degYGvalue;
    private javax.swing.JLabel degYLabel;
    private javax.swing.JSpinner degYSpinner;
    private javax.swing.JLabel degYvalue;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel grayCodeGL;
    private javax.swing.JLabel grayCodeL;
    private javax.swing.JLabel grayCodeY;
    private javax.swing.JLabel grayCodeYG;
    private javax.swing.JLabel gunMoveDir;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

    DrawingPanel drawingPanel;

    public javax.swing.JLabel getGrayCodeY() {
        return grayCodeY;
    }

    public javax.swing.JLabel getGrayCodeYG() {
        return grayCodeYG;
    }

    public javax.swing.JLabel getGunMoveDir() {
        return gunMoveDir;
    }

}
